package pojo;
// default package
// Generated Feb 16, 2016 9:29:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestTable generated by hbm2java
 */
@Entity
@Table(name = "test_table", schema = "adam_schema")
public class TestTable implements java.io.Serializable {

	/**
	 * For PostgreSQL 9.4 at least, include the annotation
	 * {@literal @}GeneratedValue(strategy = GenerationType.IDENTITY)
	 * for int primary key fields
	 */
	@Id
	@Column(name = "ident_col", unique = true, nullable = false, insertable=false, updatable=false)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long identCol;

	@Column(name = "text_col", length = 20)
	private String textCol;

	/**
	 * columns like this, with default values defined in DB, 
	 * should be set to insertable=false and updatable=false
	 * or overwrite with the code's default value; usually null
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "crte_ts", length = 29, insertable=false, updatable=false)
	private Date crteTs;

	public TestTable() {
	}

	public TestTable(long identCol) {
		this.identCol = identCol;
	}

	public TestTable(long identCol, String textCol, Date crteTs) {
		this.identCol = identCol;
		this.textCol = textCol;
		this.crteTs = crteTs;
	}

	public long getIdentCol() {
		return this.identCol;
	}

	public void setIdentCol(long identCol) {
		this.identCol = identCol;
	}

	public String getTextCol() {
		return this.textCol;
	}

	public void setTextCol(String textCol) {
		this.textCol = textCol;
	}


	public Date getCrteTs() {
		return this.crteTs;
	}

	public void setCrteTs(Date crteTs) {
		this.crteTs = crteTs;
	}

}
