package pojo;
// default package
// Generated Feb 16, 2016 9:29:45 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * TestTable generated by hbm2java
 */
@Entity
@Table(name = "test_table", schema = "adam_schema")
public class TestTable implements java.io.Serializable {

	private int identcol;
	private String textcol;

	public TestTable() {
	}

	public TestTable(int identcol) {
		this.identcol = identcol;
	}

	public TestTable(int identcol, String textcol) {
		this.identcol = identcol;
		this.textcol = textcol;
	}

	@Id
	@Column(name = "identcol", unique = true, nullable = false)
	public int getIdentcol() {
		return this.identcol;
	}

	public void setIdentcol(int identcol) {
		this.identcol = identcol;
	}

	@Column(name = "textcol", length = 20)
	public String getTextcol() {
		return this.textcol;
	}

	public void setTextcol(String textcol) {
		this.textcol = textcol;
	}

}